name: Check PR health

on: [pull_request]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install packages
      run: yarn --network-concurrency 1
    
    - name: Check linting
      run: yarn lint

  test-code:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install packages
      run: yarn --network-concurrency 1
    
    - name: Prepare Goerli subgraph
      run: NETWORK=goerli-testnet yarn prepare-subgraph
    
    - name: Run Tests
      run: yarn test